removed underscore dependencies
muqube/meteor-autoform-nouislider pull request #17
Opened 2019-08-11 13:07 UTC by jankapunkt

This PR replaces underscore related methods (`pick`, `omit`, `extend`) with native JS functions. The functions are also limited to the current usage of the package and don't provide further unnecessary functionality.

Please consider first #16 although this PR also works independently from the changes in #16

2019-08-11 20:14 UTC, raiyankamal requested changes
Let's take this opportunity to remove underscore from our versions files also. I believe you can do that by simply running the `meteor remove ...` command in your CLI. https://docs.meteor.com/commandline.html#meteorremove

2019-08-12 10:54 UTC, jankapunkt commented
@raiyankamal I think removing versions in packages only works when you publish the package. Using `meteor remove underscore` only removes underscore from the `.versions` list in the projekt, however it remains in package untouched after a rebuild.

2019-08-14 09:06 UTC, jankapunkt commented
@raiyankamal should I manually remove the package from `.versions`? It has [no other dependencies](https://github.com/meteor/meteor/blob/devel/packages/underscore/package.js), which is why it should be fine.

2019-08-16 04:02 UTC, raiyankamal approved these changes

2019-08-16 04:02 UTC, merged